config/routes.rb
ConjugMgr::Application.routes.draw do
  resources :translations

  get "pgroups/index"
  get "pgroup/:id" => "pgroups#show", as: 'pgroup'
  post "pgroups/new"
  get "pgroup/edit/:id" => "pgroups#edit", as: 'pgroup_edit'
  post '/edit_group' => "pgroups#update", as: 'edit_group'
  post '/new_group' => "pgroups#create", as: 'new_group'
  get "pgroups/update"
  get "pgroups/destroy/:id" => "pgroups#destroy", as: 'pgroup_destroy'
  get "translations/accept/:id" => "translations#accept", as: 'translation_accept'

  devise_for :users
  resources :repetitions

  resources :forms

  resources :verbs

  root :to => "verbs#practice"

  get '/download/:page' => 'verbs#download'

  get '/stats' => 'verbs#stats'

  get '/practice' => 'verbs#practice'
  get '/initiate'=> 'verbs#database_initiation'
  get '/from_json/:page' => 'verbs#download_from_json'

  post '/practice' => 'verbs#practice_draw', as: 'practice_draw'

  post '/check_form' => 'verbs#check_form', as: 'check_form'

  post '/report_transl' => 'translations#create', as: 'report_transl'

  post '/add_to_group' => 'verbs#add_to_group', as: 'add_to_group'

  post '/search' => 'verbs#search', as: 'search'

  get '/look_for/:verb' => 'verbs#look_for_conj'

  get '*path' => redirect('/')
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :verb
  belongs_to :user
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :authenticate_user!
  before_action :transl_count
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  def accept
    @translation = Translation.find(params[:id])
    @verb = @translation.verb
    @verb.update(:translation => @translation.content)
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end 
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(:content => params[:transl], :verb_id => params[:id], :user_id => current_user.id)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation.verb, notice: 'Thanks for your advice!' }
        format.json { redirect_to controller: "verbs", action: 'show', location: @translation.verb }
      else
        format.html { render action: 'new' }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:content)
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Translations proposed by users </h1>

<table>
  <thead>
    <tr>
      <th>Infinitive</th>
      <th>Translation</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.verb.infinitive %></td>
        <td><%= translation.content %></td>
        <td><%= link_to 'Accept', translation_accept_path(translation) %></td>
        <td><%= link_to 'Reject', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @translation.content %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>