config/routes.rb
ConjugMgr::Application.routes.draw do
  resources :translations

  get "pgroups/index"
  get "pgroup/:id" => "pgroups#show", as: 'pgroup'
  post "pgroups/new"
  get "pgroup/edit/:id" => "pgroups#edit", as: 'pgroup_edit'
  post '/edit_group' => "pgroups#update", as: 'edit_group'
  post '/new_group' => "pgroups#create", as: 'new_group'
  get "pgroups/update"
  get "pgroups/destroy/:id" => "pgroups#destroy", as: 'pgroup_destroy'
  get "translations/accept/:id" => "translations#accept", as: 'translation_accept'

  devise_for :users
  resources :repetitions

  resources :forms

  resources :verbs

  root :to => "verbs#practice"

  get '/download/:page' => 'verbs#download'

  get '/stats' => 'verbs#stats'

  get '/practice' => 'verbs#practice'
  get '/initiate'=> 'verbs#database_initiation'
  get '/from_json/:page' => 'verbs#download_from_json'

  post '/practice' => 'verbs#practice_draw', as: 'practice_draw'

  post '/check_form' => 'verbs#check_form', as: 'check_form'

  post '/report_transl' => 'translations#create', as: 'report_transl'

  post '/add_to_group' => 'verbs#add_to_group', as: 'add_to_group'

  post '/search' => 'verbs#search', as: 'search'

  get '/look_for/:verb' => 'verbs#look_for_conj'

  get '*path' => redirect('/')
end

app/models/pgroup.rb
class Pgroup < ActiveRecord::Base
  belongs_to :user
  has_many :ugroups
  has_many :verbs, :through => :ugroups
end

app/controllers/pgroups_controller.rb
class PgroupsController < ApplicationController
  before_filter :authenticate_user!
  before_action :transl_count
  before_action :set_pgroup, only: [:show, :edit, :update, :destroy]
  before_action :is_owner, only: [:show, :edit, :update, :destroy]



  def index
    
  end

  def show
    @groupes = ['1','2','3']     
    if params[:groupes]
      @groupes = params[:groupes]
      @verbs = @pgroup.verbs.find(:all, :conditions =>["`group` IN (?)", @groupes]).group_by{|u| u.infinitive[0]}
    else
      @verbs = @pgroup.verbs.group_by{|u| u.infinitive[0]}
    end
  end

  def new
    @pgroup = Pgroup.new
  end

  def edit
    @groupes = Array.new()
    @verbs = Array.new()
    @excluded_verbs = Array.new()
    
    for i in 1..3
      v = @pgroup.verbs.where(:group => i, :id => 0..92)
      gr = Verb.where(:group => i, :id => 0..92)
      if v.length == gr.length
        @groupes.push(i.to_s)
      else
        if (i == 3 and gr.length - v.length < 10) or (i == 2 and gr.length - v.length < 4) or ( i==1 and gr.length - v.length < 9)
          @groupes.push(i.to_s)
          @excluded_verbs = @excluded_verbs + (gr - v)
        else
          @verbs = @verbs + v
        end
      end
    end
    @verbs = @verbs + @pgroup.verbs.where(:id => 93..1900) 
    if @verbs.length
      @verbs.map! { |e| e.infinitive }
      @verbs = @verbs.join(", ")
    else
      @verbs = ""
    end
    if @excluded_verbs.length
      @excluded_verbs.map! { |e| e.infinitive }
      @excluded_verbs = @excluded_verbs.join(", ")
    else
      @excluded_verbs = ""
    end
  end

  def update
    @gr_to_pr = params[:groupes]
    @excl_to_pr = params[:excluded_verbs].length > 0 ? params[:excluded_verbs].split(', ') : ''
    @add_to_pr = params[:verbs].length > 0 ? params[:verbs].split(', ') : ''

    #which verbs
    if @add_to_pr != ''
      check_if_in_db(@add_to_pr)
    end
    @verbs =  Verb.find(:all, :conditions =>
      ["(`group` IN (?) AND `infinitive` NOT IN (?) AND `id` IN (?)) OR `infinitive` IN (?) ",
      @gr_to_pr, @excl_to_pr, (0..94), @add_to_pr ])

    respond_to do |format|
      if @pgroup.update(:name => params[:name], :verbs => @verbs)
        format.html { redirect_to @pgroup, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @pgroup = Pgroup.new(:name => params[:name], :user_id => current_user.id)
    @gr_to_pr = params[:groupes]
    @excl_to_pr = params[:excluded_verbs].length > 0 ? params[:excluded_verbs].split(', ') : ''
    @add_to_pr = params[:verbs].length > 0 ? params[:verbs].split(', ') : ''
      
    if @add_to_pr != ''
      check_if_in_db(@add_to_pr)
    end

    @verbs =  Verb.find(:all, :conditions =>
      ["(`group` IN (?) AND `infinitive` NOT IN (?) AND `id` < 95) OR `infinitive` IN (?) ",
      @gr_to_pr, @excl_to_pr, @add_to_pr ])

    @pgroup.verbs = @verbs

    respond_to do |format|
      if @pgroup.save
        format.html { redirect_to @pgroup, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pgroup }
      else
        format.html { render action: 'new' }
        format.json { render json: @pgroup.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @pgroup = Pgroup.find(params[:id])
    @pgroup.destroy
    respond_to do |format|
      format.html { redirect_to pgroups_index_url }
      format.json { head :no_content }
    end

  end

  def check_if_in_db(collection)
    not_in_db = Array.new()
    
    #which verbs
    collection.each do |v|
      if Verb.where(:infinitive => v).count == 0
        # we have to group all the verbs that should be added to DB
        # it's better than adding it immediatly cause we will have to run through 196 json files once
        not_in_db.push(v)
      end
    end

    for i in 1..198
      file = File.read("public/temp_#{i}.json")
      verbs_conj = JSON.parse(file)
      verbs_conj.each do |verb|
        if not_in_db.include?(verb["infinitive"]) 
          v = Verb.new(:infinitive => verb["infinitive"], :translation => verb["translation"], :group => verb["group"])
          if v.save
            @tenses.each_with_index do |tense, index|
              @forms.each_with_index do |form, index2|
                if(verb[tense.to_s][form.to_s].strip != '')
                  @form = Form.new(:content => verb[tense.to_s][form.to_s], :temp => index.to_i, :person => index2.to_i,:verb => v)
                  @form.save
                end
              end
            end
          end
        end
      end
    end  
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pgroup
      @pgroup = Pgroup.find(params[:id])
    end

    def is_owner
      unless current_user && current_user.id == @pgroup.user.id
        flash[:notice] = "You are not the owner of this group"
        redirect_to root_path
      end   
    end
end

app/helpers/pgroups_helper.rb
module PgroupsHelper
end

app/views/pgroups/_form_edit_group.html.erb
<%= form_tag(edit_group_path, method: "post") do %>
  <div class="row step choose_tense">
    <b>Step I: Choose the name</b> 
    <%= text_field_tag 'name', @pgroup.name, :required => true %><br>
  </div>
  <br>
  <div class="row step">
    <b>Step II: Choose groupes</b><br/>
    <br>
    <%= check_box_tag 'groupes[]', '1', checked=(@groupes.include? '1')  %> I
    <%= check_box_tag 'groupes[]', '2', checked=(@groupes.include? '2')  %> II
    <%= check_box_tag 'groupes[]', '3', checked=(@groupes.include? '3')  %> III
    <br/>
    <br>
    <b>...or specifie verbs</b><br>
    <%= text_area_tag 'verbs', @verbs, rows: 10, cols:40 %><br>
    <b>...or exclude verbs </b><br>
    <%= text_area_tag 'excluded_verbs', @excluded_verbs, rows: 10, cols:40  %><br>
    <%= hidden_field_tag 'id', @pgroup.id %>
  </div>
  <%= submit_tag "Update"%>
<% end %>

app/views/pgroups/_form_new_group.erb
<%= form_tag(new_group_path, method: "post") do %>
  <div class="row step choose_tense">
    <b>Step I: Choose the name</b> 
    <%= text_field_tag 'name', nil, placeholder: 'My extraordinary group', :required => true %><br>
  </div>
  <br>
  <div class="row step">
    <b>Step II: Choose verbs</b><br/>
    <br>
    Group(s)
    <%= check_box_tag 'groupes[]', '1', checked=false  %> I
    <%= check_box_tag 'groupes[]', '2', checked=false  %> II
    <%= check_box_tag 'groupes[]', '3', checked=false  %> III
    <br/>
    <br>
    <b>...or specifie verbs</b><br>
    <%= text_area_tag 'verbs', nil, placeholder: 'être, aller, venir...', rows: 10, cols:40  %><br>
    <b>...or exclude verbs </b><br>
    <%= text_area_tag 'excluded_verbs', nil, placeholder: 'être, aller, venir...', rows: 10, cols:40  %><br>
  </div>
  <%= submit_tag "Create group!"%>
<% end %>

app/views/pgroups/destroy.html.erb
<h1>Pgroups#destroy</h1>
<p>Find me in app/views/pgroups/destroy.html.erb</p>

app/views/pgroups/edit.html.erb
<%= render 'form_edit_group' %>

<%= link_to 'Back', verbs_path %>

app/views/pgroups/index.html.erb
<h1>Manage your groups</h1>
<%= button_to "Add new", pgroups_new_path %>
<ol>
	<% current_user.pgroups.each do |group| %>
	<li> <%= group.name %> 
		<%= link_to 'Show', pgroup_path(group.id) %>
		<%= link_to 'Edit', pgroup_edit_path(group.id) %>
		<%= link_to 'Remove', pgroup_destroy_path(group.id), data: { confirm: 'Are you sure?' } %>
	</li>
	<% end %>
</ol>

app/views/pgroups/new.html.erb
<h1>Create your own new group of verbs</h1>

<%= render 'form_new_group' %>

<%= link_to 'Back', verbs_path %>

app/views/pgroups/show.html.erb
<h1><%= @pgroup.name%> <%= link_to '[edit]', pgroup_edit_path(@pgroup.id) %></h1>



<%= link_to image_tag("up.gif", :border => 0), pgroup_path(@pgroup.id, anchor: 'home'), :class => 'up_home' %>
<% l = ('A' .. 'Z').to_a %>
<% l.push('é','ê') %>
<div id="sorting_options">
  <% l.each do |letter| %>
   <%= link_to letter, pgroup_path(@pgroup.id,anchor: letter) %><br>
  <% end %>
</div>

<!-- <table>
  <thead>
    <tr>
      <th>Infinitive</th>
      <th>Translation</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead> -->

    <% @verbs.keys.sort.each do |starting_letter| %>
      <div id="<%=starting_letter.capitalize %>">
      <%= starting_letter.capitalize %>
      <table class="verbs_list">
      
      <% @verbs[starting_letter].each do |verb| %>
        <tr>
          <td><%= verb.infinitive %></td>
          <td><%= verb.translation %></td>
          <td><%= verb.group %></td>

          <td><%= link_to 'Show', verb %></td>
          <% if current_user && current_user.role == 'admin' %>
            <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
            <td><%= link_to 'Destroy', verb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <% end %>

app/views/pgroups/update.html.erb
<h1>Pgroups#update</h1>
<p>Find me in app/views/pgroups/update.html.erb</p>