config/routes.rb
ConjugMgr::Application.routes.draw do
  resources :translations

  get "pgroups/index"
  get "pgroup/:id" => "pgroups#show", as: 'pgroup'
  post "pgroups/new"
  get "pgroup/edit/:id" => "pgroups#edit", as: 'pgroup_edit'
  post '/edit_group' => "pgroups#update", as: 'edit_group'
  post '/new_group' => "pgroups#create", as: 'new_group'
  get "pgroups/update"
  get "pgroups/destroy/:id" => "pgroups#destroy", as: 'pgroup_destroy'
  get "translations/accept/:id" => "translations#accept", as: 'translation_accept'

  devise_for :users
  resources :repetitions

  resources :forms

  resources :verbs

  root :to => "verbs#practice"

  get '/download/:page' => 'verbs#download'

  get '/stats' => 'verbs#stats'

  get '/practice' => 'verbs#practice'
  get '/initiate'=> 'verbs#database_initiation'
  get '/from_json/:page' => 'verbs#download_from_json'

  post '/practice' => 'verbs#practice_draw', as: 'practice_draw'

  post '/check_form' => 'verbs#check_form', as: 'check_form'

  post '/report_transl' => 'translations#create', as: 'report_transl'

  post '/add_to_group' => 'verbs#add_to_group', as: 'add_to_group'

  post '/search' => 'verbs#search', as: 'search'

  get '/look_for/:verb' => 'verbs#look_for_conj'

  get '*path' => redirect('/')
end

app/models/verb.rb
class Verb < ActiveRecord::Base
  has_many :translations, :dependent => :destroy
  has_many :forms, :dependent => :destroy
  has_many :ugroups
  has_many :pgroups, :through => :ugroups
  validates :infinitive, uniqueness: true
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_verb, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :practice, :practice_draw, :check_form, :index]
  helper_method :get_interval
  before_action :transl_count
  before_filter :require_admin, only: [:new, :create, :edit, :update, :destroy, :database_initiation]

  # GET /verbs
  # GET /verbs.json
  def index
    @groupes = ['1','2','3']
    if params[:groupes]
      @groupes = params[:groupes]
      @verbs =  Verb.find(:all, :conditions =>["`id` < 95 AND `group` IN (?)", @groupes]).group_by{|u| u.infinitive[0]}
    else
      @verbs = Verb.where(:id => 0..94).group_by{|u| u.infinitive[0]}
    end
    if current_user 
      @v_best = Array.new()
      @v_worst = Array.new()
      a = ActiveRecord::Base.connection.execute("select v.id AS vid, SUM(CAST(r.mistake AS float)/CAST(r.count AS float)) AS s from repetitions r, forms f, verbs v WHERE r.user_id = #{current_user.id} AND r.form_id = f.id AND f.verb_id = v.id GROUP BY v.id ORDER BY s DESC LIMIT 5")
      b = ActiveRecord::Base.connection.execute("select v.id AS vid, SUM(CAST(r.mistake AS float)/CAST(r.count AS float)) AS s from repetitions r, forms f, verbs v WHERE r.user_id = #{current_user.id} AND r.form_id = f.id AND f.verb_id = v.id GROUP BY v.id ORDER BY s ASC LIMIT 5")
      a.each do |v|
        @v_worst.push(v["vid"].to_i)
      end
      b.each do |v|
        @v_best.push(v["vid"].to_i)
      end
      @v_best = @v_best - @v_worst
    end
  end

  # GET /verbs/1
  # GET /verbs/1.json
  def show
    @verb_forms = @verb.forms
    @verb_forms_tab = Hash.new
    @tenses.each_with_index do |tense, index|
      @verb_forms_tab[tense] = Hash.new
      @forms.each_with_index do |form, index2|
        temp = @verb_forms.where(:temp => index.to_i, :person => index2.to_i).first
        @verb_forms_tab[tense][form] = temp ? temp.content : ''
      end
    end

  end

  # GET /verbs/new
  def new
    @verb = Verb.new
  end

  # GET /verbs/1/edit
  def edit
  end

  # POST /verbs
  # POST /verbs.json
  def create
    @verb = Verb.new(:infinitive => verb_params[:infinitive], :translation => verb_params[:translation], :group => verb_params[:group])
    if @verb.save
      @tenses.each_with_index do |tense, index|
        @forms.each_with_index do |form, index2|
          if(verb_params[tense][form].strip != '')
            @form = Form.new(:content => verb_params[tense][form], :temp => index.to_i, :person => index2.to_i,:verb => @verb)
            @form.save
          end
        end
      end
    end

    respond_to do |format|
      if @verb.save
        format.html { redirect_to @verb, notice: 'Verb was successfully created.' }
        format.json { render action: 'show', status: :created, location: @verb }
      else
        format.html { render action: 'new' }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_to_group
    @verb = Verb.find(params[:id].to_i)
    pgroup = Pgroup.find(params[:group_id])
    verbs = pgroup.verbs
    if verbs.include?(@verb)
      message = "This verb is already added to this group"
    else
      message = 'Verb was successfully added.' 
      verbs.push(@verb)
    end

    respond_to do |format|
      if pgroup.update(:verbs => verbs)
        format.html { redirect_to @verb, notice: message}
        format.json { render action: 'show', status: :created, location: @verb }
      else
        format.html { redirect_to @verb, notice: 'Verb was NOT added.' }
        format.json { render action: 'show', status: :created, location: @verb }
      end
    end
  end

  # PATCH/PUT /verbs/1
  # PATCH/PUT /verbs/1.json
  def update
    respond_to do |format|
      if @verb.update(verb_params)
        format.html { redirect_to @verb, notice: 'Verb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verbs/1
  # DELETE /verbs/1.json
  def destroy
    @verb.destroy
    respond_to do |format|
      format.html { redirect_to verbs_url }
      format.json { head :no_content }
    end
  end

  #downloading from figaro => json
  def download
    page = params[:page].to_i

    a = download_conjugation(page)
    @verbs_conj.each do |verb|
      v = Verb.new(:infinitive => verb[:infinitive], :translation => verb[:translation], :group => verb[:group])
      if v.save
        @tenses.each_with_index do |tense, index|
          @forms.each_with_index do |form, index2|
            if(verb[tense][form].strip != '')
              @form = Form.new(:content => verb[tense][form], :temp => index.to_i, :person => index2.to_i,:verb => v)
              @form.save
            end
          end
        end
      end
    end
    File.open("public/temp_#{page}.json","w") do |f|
      f.write(JSON.pretty_generate(@verbs_conj))
    end

    @verbs = Verb.all
    respond_to do |format|
      format.html{ render action: 'index'}
      format.json { head :no_content }
    end

  end

  def search
    @search_form = params[:search]
    # we have to take care of auxiliary verbs
    # we assume that user is not looking for the form of etre or avoir
    flag = 0
    exact_forms = Form.where(content: @search_form)

    @exact_verbs = Array.new()
    @similar_verbs = Array.new()
    @infinitives = Verb.where("infinitive LIKE ?", "%#{@search_form}%")

    if exact_forms
      exact_forms.each_with_index do |form, index|
        # We need to know which verb and which tense is it
        v = Array.new()
        a = Verb.find(form.verb_id)
        v.push(Verb.find(form.verb_id))
        v.push(@tenses[form.temp])
        v.push(@forms[form.person].to_s + " " +form.content)
        @exact_verbs.push(v)
        if a.infinitive == "être" || a.infinitive == "avoir"
          flag = 1
        end
      end
    end

    if flag == 0
      similar_forms = Form.where("content LIKE ?", "%#{@search_form}%")

      similar_forms = similar_forms - exact_forms
      if similar_forms
        similar_forms.each_with_index do |form, index|
          v = Array.new()

          v.push(form.verb)
          v.push(@tenses[form.temp])
          v.push(@forms[form.person].to_s + " " +form.content)
          @similar_verbs.push(v)
        end
      end
    end    
  end

  def look_for_conj
    verb = download_verb_conjugation(params[:verb])
    v = Verb.new(:infinitive => verb[:infinitive], :translation => verb[:translation], :group => verb[:group])
    if v.save
      @tenses.each_with_index do |tense, index|
        @forms.each_with_index do |form, index2|
          if(verb[tense][form].strip != '')
            @form = Form.new(:content => verb[tense][form], :temp => index.to_i, :person => index2.to_i,:verb => v)
            @form.save

          end
        end
      end
    end
    respond_to do |format|
      if v.save
        format.html { redirect_to v, notice: 'Verb was successfully created.' }
        format.json { render action: 'show', status: :created, location: v }
      else
        format.html { render action: 'new' }
        format.json { render json: v.errors, status: :unprocessable_entity }
      end
    end
  end

  def download_from_json
    page = params[:page].to_i

    for i in 0..10
      file = File.read("public/temp_#{page}.json")
      verbs_conj = JSON.parse(file)
      verbs_conj.each do |verb|
        v = Verb.new(:infinitive => verb["infinitive"], :translation => verb["translation"], :group => verb["group"])
        if v.save
          @tenses.each_with_index do |tense, index|
            @forms.each_with_index do |form, index2|
              if(verb[tense.to_s][form.to_s].strip != '')
                @form = Form.new(:content => verb[tense.to_s][form.to_s], :temp => index.to_i, :person => index2.to_i,:verb => v)
                @form.save
              end
            end
          end
        end
      end
      page = page+1
    end

    respond_to do |format|
      format.html{ redirect_to action: 'index'}
      format.json { head :no_content }
    end
  end

  def practice
    if current_user
      @pgroups = Array.new()
      current_user.pgroups.each { |p| 
        a = {:name => p.name, :id => p.id}
        @pgroups.push(a)
       }  
    end
  end

  def practice_draw

    session[:random] = params.has_key?(:random) ? params[:random] : 0
    session[:no_follow] = params.has_key?(:no_follow) ? params[:no_follow] : 0

    r = 0;
    @error_message = Array.new()

    @random = session[:random]

    @excl_to_pr = validate_verbs_list(params[:excluded_verbs])
    if @excl_to_pr == 0
      @error_message.push("Incorrect format 'exclude verbs'. ")
      r = 1;
    end
    @add_to_pr = validate_verbs_list(params[:verbs])
    if @add_to_pr == 0
      @error_message.push("Incorrect format 'specifie verbs'. ")
      r = 1;
    end

    if !params.has_key?(:tenses) 
      @error_message.push("You have to choose at least one tense. ")
      r = 1;
    else
      @tenses_to_pr = Array.new()
      params[:tenses].each do |key, val|
        @tenses_to_pr.push(val)
      end
    end
    if (!params.has_key?(:groupes) && @excl_to_pr.empty? && @add_to_pr.empty?)
      @error_message.push("You have to choose at least one verb")
      r=1;
    end

    if r == 0
      if params.has_key?(:pgroup_id) && params[:pgroup_id] != ''
        p = Pgroup.find(params[:pgroup_id].to_i)
        if p && current_user.pgroups.include?(p)
          @verbs_to_pr = p.verbs
        else
          r = 1
          @error_message.push("Wrong group of verbs")
        end
      else
        @gr_to_pr = params[:groupes]

        #which verbs
        @verbs_to_pr =  Verb.find(:all, :conditions =>
          ["(`group` IN (?) AND `infinitive` NOT IN (?)) OR `infinitive` IN (?) AND `id` < 95 ",

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/verbs/_form.html.erb
<%= form_for(@verb) do |f| %>
  <% if @verb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verb.errors.count, "error") %> prohibited this verb from being saved:</h2>

      <ul>
      <% @verb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :infinitive %><br>
    <%= f.text_field :infinitive %>
  </div>
  <div class="field">
    <%= f.label :translation %><br>
    <%= f.text_field :translation %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.select :group, [['I', 1], ['II', 2], ['III', 3]] %>
  </div>

    <% @tenses.each_with_index do |tense, index| %>
    <% if (index%3) == 0 %>
      <div class="row">
    <% end %>
      <div class="large-4 columns">
        <h3><%= tense.to_s.capitalize.gsub(/[_]/, ' ')%></h3>
        <%= f.fields_for tense do |pr| %>
          <% @forms.each do |form| %>
            <%= pr.label form %>
            <%= pr.text_field form %>
          <% end %>
        <% end %>
      </div>
    <% if (index%3) == 2 %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/verbs/_form_practice.html.erb
<%= form_tag(practice_draw_path, method: "post") do %>
  <div class="row step choose_tense">
    <b>Step I: Choose tenses</b> <button type="button" id="uncheck_all" data-check="1"> Uncheck all </button><br/>
    <br>
    <% @tenses.each_with_index do |tense, index| %>
      <div class="tenses"><%= check_box_tag 'tenses['+tense.to_s+']', index, checked=@tenses_to_pr ? @tenses_to_pr.include?(index.to_s) : true %> <%= tense.to_s.capitalize.gsub(/[_]/, ' ')%></DIV>
    <% end %>
  </div>
  <br>
  <div class="row step">
    <b>Step II: Choose verbs</b><br/>
    <br>
    Group(s)
    <%= check_box_tag 'groupes[]', '1', checked=true  %> I
    <%= check_box_tag 'groupes[]', '2', checked=true  %> II
    <%= check_box_tag 'groupes[]', '3', checked=true  %> III
    <br/>
    <br>
    <b>...specifie verbs (out of chosen groups)</b><br>
    <%= text_field_tag 'verbs', @add_to_pr, placeholder: 'être, aller, venir...' %><br>
    <b>...exclude verbs (from chosen groups) </b><br>
    <%= text_field_tag 'excluded_verbs', @excl_to_pr, placeholder: 'être, aller, venir...' %><br>
    <% if user_signed_in? %>

    <br>
      <b>...or choose one of your own groups  </b><br>
      <%= select_tag "pgroup_id", options_from_collection_for_select(current_user.pgroups, "id", "name"), prompt: "Choose your group"
%><br><br>
     <%= check_box_tag 'random' %> Choose forms by random
     <%= check_box_tag 'no_follow' %> Don't follow my answers

    <% end %>
  </div>
  <%= submit_tag "Try me!"%>
<% end %>

app/views/verbs/_search_form.html.erb
<%= form_tag(search_path, method: "post") do %>
    <%= text_field_tag 'search' %>
  <%= submit_tag "Search for"%>
<% end %>

app/views/verbs/edit.html.erb
<h1>Editing verb</h1>

<%= render 'form' %>

<%= link_to 'Show', @verb %> |
<%= link_to 'Back', verbs_path %>

app/views/verbs/index.html.erb
<h1>Listing verbs</h1>
<%= form_tag(verbs_path, method: "get") do %>
  Groupes
  <%= check_box_tag 'groupes[]', '1', @groupes.include?('1')  %> I
  <%= check_box_tag 'groupes[]', '2', @groupes.include?('2')  %> II
  <%= check_box_tag 'groupes[]', '3', @groupes.include?('3')  %> III
  <%= submit_tag "Refresh"%>
<% end %>
<%= link_to image_tag("up.gif", :border => 0), verbs_path(anchor: 'home'), :class => 'up_home' %>
<% l = ('A' .. 'Z').to_a %>
<% l.push('é','ê') %>
<div id="sorting_options">
  <% l.each do |letter| %>
   <%= link_to letter, verbs_path(anchor: letter) %><br>
  <% end %>
</div>

<!-- <table>
  <thead>
    <tr>
      <th>Infinitive</th>
      <th>Translation</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead> -->

    <% @verbs.keys.sort.each do |starting_letter| %>
      <div id="<%=starting_letter.capitalize %>">
      <%= starting_letter.capitalize %>
      <table class="verbs_list">
      <% @verbs[starting_letter].each do |verb| %>
        <tr>
          <% if user_signed_in? && @v_best.include?(verb.id) %>
          <td class="green">
          <% elsif user_signed_in? && @v_worst.include?(verb.id) %>
          <td class="red">
            <% else %>
          <td>
          <% end %>
          <%= verb.infinitive %></td>
          <td><%= verb.translation %></td>
          <td><%= verb.group %></td>
          <td><%= link_to 'Show', verb %></td>
          <% if current_user && current_user.role == 'admin' %>
          <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
          <td><%= link_to 'Destroy', verb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    </div>
    <% end %>

      
  <!-- </tbody> -->
<!-- </table> -->

<br>

app/views/verbs/new.html.erb
<h1>New verb</h1>

<%= render 'form' %>

<%= link_to 'Back', verbs_path %>

app/views/verbs/practice.html.erb
<div class="row">
  <% if @error_message && @error_message.count %>
	  <div class="error">
	  	<b>UPS!</b><br>
	  	<% @error_message.each do |e| %>
	  		<%= e %> <br>
	  	<% end %>
	  </div>
  <% end %>

  <div id="practice_form">
    <%= render 'form_practice' %>

    <br><br>
  </div>
</div>

app/views/verbs/practice_draw.erb
<h1>Show me you know me!</h1>

<% if @result == 1 %>
  <div> <span class="correct" >CORRECT! </span><br>
    <%= @forms[@f_old.person.to_i].to_s.capitalize %>
    (<%= @v_old.infinitive %>, <%= @tenses[@f_old.temp.to_i].to_s.gsub(/[_]/, ' ') %>)
    <span class="correct" > <%= @correct %> </span>
  </div>
<% elsif @result == 0 %>
  <div> <span class="wrong"> WRONG!  </span>
  <%= @forms[@f_old.person.to_i].to_s.capitalize %>
    (<%= @v_old.infinitive %>, <%= @tenses[@f_old.temp.to_i].to_s.gsub(/[_]/, ' ') %>)
    <span class="wrong"><%= @answer %> </span> <span class="correct"> <%= @correct %> </span>
  </div>
<% end %>
  <%= form_tag(check_form_path, method: "post") do %>
<% if @result && user_signed_in? && @no_follow == 0%>
  <div> <span> Grade yourself </span>
    (default: for the correct answer 4, for the incorrect - 1)
    <table><tr><td>
    <%= radio_button_tag 'q', '1', @result == 0  %> 1 <br> blackout! </td>
    <td><%= radio_button_tag 'q', '2'  %> 2 <br> </td>
    <td><%= radio_button_tag 'q', '3'  %> 3<br></td>
    <td><%= radio_button_tag 'q', '4', @result == 1  %>4 <br></td>
    <td><%= radio_button_tag 'q', '5'  %> 5 <br> know it by heart </td>
    <%= hidden_field_tag 'full_form_id', @f_old.id %>
    </tr></table>
  </div>
<% end %>


<h2>Verb: <%= @v.infinitive %> <%= link_to '>>', @v %> </h2>
<button type="button" id="show_trans">what does it mean...?</button>
<div id="trans" class="hide"><%= @v.translation %></div>
<h2>Tense: <%= @tenses[@f.temp.to_i].to_s.capitalize.gsub(/[_]/, ' ') %>          </h2>
<!-- <div> -->
  <h2> <%= @forms[@f.person.to_i].to_s.capitalize %>: </h2>

    <%= text_field_tag 'answer' %>

    <%= hidden_field_tag 'forms_to_pr_id', @forms_to_pr_id %>
    <%= hidden_field_tag 'form', @f.id %>
    <% if user_signed_in? && @random == 0  %>
      <%= hidden_field_tag 'forms_A', @forms_A %>
      <%= hidden_field_tag 'forms_B', @forms_B %>
      <%= hidden_field_tag 'forms_C', @forms_C %>
      <%= hidden_field_tag 'flag', @flag %>

    <% end %>


    <%= submit_tag "Check me!"%>
    <div id="special_char">
      <% ['à', 'ç', 'é', 'è', 'ê', 'î', 'ï', 'û'].each do |letter| %>
        <button type="button" role="button"> <%= letter %> </button>
      <% end %>
    </div>
  <% end %>

</div>
<%= link_to "Change parametres", controller: "verbs", action: "practice" %>

app/views/verbs/search.html.erb
<h1>Searching results</h1>

<h2>You were looking for "<%= @search_form %>"</h2>
<% if @exact_verbs.length == 0 && @similar_verbs.length == 0 && @infinitives.length == 0 %>
<h2> No verbs matching! </h2>
<% else %>
  <div>
    <h2> 'Exact' results</h2>
    <% if @exact_verbs.length == 0 %>
      No exact forms founded 
    <% else %>
      <table class="search_res">
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Translation</th>
            <th>Temps</th>
            <th>Personne</th>
          </tr>
        </thead>

        <tbody>
          <% @exact_verbs.each do |verb| %>
            <tr>
              <td><%= link_to verb[0].infinitive, verb[0] %></td>
              <td><%= verb[0].translation %></td>
              <td><%= verb[1].to_s.capitalize.gsub(/[_]/, ' ')%> </td>
              <td><%= verb[2]%> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div>
    <h2>"...plus ou moins..."</h2>
    <% if @similar_verbs.length == 0 %>
      No similar forms founded 
    <% else %>
      <table class="search_res">
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Translation</th>
            <th>Temps</th>
            <th>Personne</th>
          </tr>
        </thead>

        <tbody>
          <% @similar_verbs.each do |verb| %>
            <tr>
              <td><%= link_to verb[0].infinitive, verb[0] %></td>
              <td><%= verb[0].translation %></td>
              <td><%= verb[1].to_s.capitalize.gsub(/[_]/, ' ')%> </td>
              <td><%= verb[2]%> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div>
    <h2>Infinitives</h2>
    <% if @infinitives.length == 0 %>
      No infinitives founded 
    <% else %>
      <table class="search_res">
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Translation</th>
          </tr>
        </thead>

        <tbody>
          <% @infinitives.each do |verb| %>
            <tr>
              <td><%= link_to verb.infinitive, verb %></td>
              <td><%= verb.translation %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>

app/views/verbs/show.html.erb
<p>
  <strong>Infinitive:</strong>
  <%= @verb.infinitive %>
  <% if user_signed_in? %>
    <br>
    <%= form_tag(add_to_group_path, method: "post") do %>
      <%= select_tag "group_id", options_from_collection_for_select(current_user.pgroups, "id", "name"), prompt: "Add to my group" 
      %>
      <%= hidden_field_tag 'id', @verb.id %>
    <%= submit_tag "Add me!"%>
    <% end %>
  <% end %>

</p>

<p>
  <strong>Translation:</strong>
  <%= @verb.translation %>
  <div id="report_transl">
    <%= form_tag(report_transl_path, method: "post") do %>
      I think this will be better... <%= text_field_tag "transl" %>
      <%= hidden_field_tag 'id', @verb.id %>
    <%= submit_tag "Report!"%>
    <% end %>
  </div>
</p>

<p>
  <strong>Group:</strong>
  <%= @verb.group %>
</p>

<h2> Conjugaison </h2>
 <% @tenses.each_with_index do |tense, index| %>
    <% if (index%3) == 0 %>
      <div class="row">
    <% end %>
      <div class="large-4 columns">
        <h3><%= tense.to_s.capitalize.gsub(/[_]/, ' ')%></h3>

          <% @forms.each do |form| %>
           <b> <%= form %>:</b>
            <%= @verb_forms_tab[tense][form] %>
          <% end %>

      </div>
    <% if (index%3) == 2 %>
      </div>
    <% end %>
  <% end %>

<%= link_to 'Edit', edit_verb_path(@verb) %> |
<%= link_to 'Back', verbs_path %>

app/views/verbs/stats.html.erb
<h1> Your Stats! </h1>

<h2> VERBS </h2>
<h3>...<%= @worst_v_count %> hardest verbs:</h3>
<%= form_tag(stats_path, method: "get") do %>
  Chamge number
  <%= select_tag 'worst_v_count', options_for_select(1..10)%>
  <%= submit_tag "Refresh"%>
<% end %>
<table class="verbs_list">
	<% @v_worst.each do |verb| %>
    <tr>
      <td>
      <%= verb.infinitive %></td>
      <td><%= verb.translation %></td>
      <td><%= verb.group %></td>
      <td><%= link_to 'Show', verb %></td>
      <% if current_user && current_user.role == 'admin' %>
      <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
      <td><%= link_to 'Destroy', verb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<h3>...<%= @best_v_count %> easiest verbs:</h3>
<%= form_tag(stats_path, method: "get") do %>
  Chamge number
  <%= select_tag 'best_v_count', options_for_select(1..10)%>
  <%= submit_tag "Refresh"%>
<% end %>
<table class="verbs_list">
	<% @v_best.each do |verb| %>
    <tr>
      <td>
      <%= verb.infinitive %></td>
      <td><%= verb.translation %></td>
      <td><%= verb.group %></td>
      <td><%= link_to 'Show', verb %></td>
      <% if current_user && current_user.role == 'admin' %>
      <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
      <td><%= link_to 'Destroy', verb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<h2> FORMS </h2>
<h3>...<%= @worst_f_count %> hardest forms:</h3>
<%= form_tag(stats_path, method: "get") do %>
  Chamge number
  <%= select_tag 'worst_f_count', options_for_select(1..10)%>
  <%= submit_tag "Refresh"%>
<% end %>
<table class="verbs_list">
	<% @f_worst.each do |form| %>
    <tr>
      <td>
      <%= form.verb.infinitive %></td>
      <td><%= form.verb.translation %></td>
      <td><%= form.verb.group %></td>
      <td><%= @tenses[form.temp.to_i].to_s.capitalize.gsub(/[_]/, ' ') %></td>
      <td><%= @forms[form.person.to_i].to_s.capitalize %></td>
      <td><%= form.content.upcase %> </td>
    </tr>
  <% end %>
</table>

<h3>...<%= @best_f_count %> easiest forms:</h3>
<%= form_tag(stats_path, method: "get") do %>
  Chamge number
  <%= select_tag 'best_f_count', options_for_select(1..10)%>
  <%= submit_tag "Refresh"%>
<% end %>
<table class="verbs_list">
	<% @f_best.each do |form| %>
    <tr>
      <td>
      <%= form.verb.infinitive %></td>
      <td><%= form.verb.translation %></td>
      <td><%= form.verb.group %></td>
      <td><%= @tenses[form.temp.to_i].to_s.capitalize.gsub(/[_]/, ' ') %></td>
      <td><%= @forms[form.person.to_i].to_s.capitalize %></td>
      <td><%= form.content.upcase %> </td>
    </tr>
  <% end %>
</table>