config/routes.rb
ConjugMgr::Application.routes.draw do
  resources :translations

  get "pgroups/index"
  get "pgroup/:id" => "pgroups#show", as: 'pgroup'
  post "pgroups/new"
  get "pgroup/edit/:id" => "pgroups#edit", as: 'pgroup_edit'
  post '/edit_group' => "pgroups#update", as: 'edit_group'
  post '/new_group' => "pgroups#create", as: 'new_group'
  get "pgroups/update"
  get "pgroups/destroy/:id" => "pgroups#destroy", as: 'pgroup_destroy'
  get "translations/accept/:id" => "translations#accept", as: 'translation_accept'

  devise_for :users
  resources :repetitions

  resources :forms

  resources :verbs

  root :to => "verbs#practice"

  get '/download/:page' => 'verbs#download'

  get '/stats' => 'verbs#stats'

  get '/practice' => 'verbs#practice'
  get '/initiate'=> 'verbs#database_initiation'
  get '/from_json/:page' => 'verbs#download_from_json'

  post '/practice' => 'verbs#practice_draw', as: 'practice_draw'

  post '/check_form' => 'verbs#check_form', as: 'check_form'

  post '/report_transl' => 'translations#create', as: 'report_transl'

  post '/add_to_group' => 'verbs#add_to_group', as: 'add_to_group'

  post '/search' => 'verbs#search', as: 'search'

  get '/look_for/:verb' => 'verbs#look_for_conj'

  get '*path' => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConjugMgr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="home">
    <div class="upper_div">
      <font size="2"><a id="small_a">A</a></font>
<font size="4"><a id="medium_a">A</a></font>
<font size="5"><a id="big_a">A</a></font>
      <%= render :partial => 'verbs/search_form' %></div>
<div id="content">
 <% if user_signed_in? && current_user.role == 'admin' %>
 <p> Hello Admin! Your application did miss you! </p>
 <% end %>
 <p class="navbar-text pull-right" role="navigation">
  <%= link_to 'Let\'s do it!', root_path, :class => 'navbar-link', :accesskey => "x"%> |
  <%= link_to 'Verbs list', verbs_path, :class => 'navbar-link', :accesskey => "l" %> |||

  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link', :accesskey => "q"  %>
    |
    <%= link_to "Your groups", pgroups_index_path, :class => 'navbar-link', :accesskey => "g"  %>
    |
    <%= link_to "Your stats", stats_path, :class => 'navbar-link'  %>
    |
    <% if current_user.role == 'admin' %>
      <%= link_to "Translations to verify! (#{@translation.count})", translations_path, :class => 'navbar-link'  %>
    <% end %>


  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

  <% end %>
 </p>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>

<footer>
  <hr>
<div>
  <b>Who and why:</b>
  <br>
  The application was created by <%= mail_to "acyganiewicz@gmail.com", "Alicja Cyganiewicz", :class => 'navbar-link'%> as the final project for a master's degree in the field of Electronic information processing at Jagiellonian University.
</div>
<div>
  <b>Goal: </b><br>
  The application serves to practice conjugation of french verbs. For registered users the exercices are adjusted to their progress.
</div>
<div>
  <b>Supervisor</b>:
  <br><span>Dr hab. Janusz Jurek</span>
</div>

<div class="note">
<hr>
  Autorem niniejszego serwisu jest Alicja Cyganiewicz <br>
Serwis ten stanowi integralną część pracy magisterskiej z Elektronicznego Przetwarzania Informacji, przygotowanej pod kierunkiem dr. hab. Janusza Jurka na Wydziale Zarządzania i Komunikacji Społecznej Uniwersytetu Jagiellońskiego.
</div>
<div class="copyright">
  Copyright &copy; <%= Time.now.year %> Alicja Cyganiewicz. All rights reserved
</div>
</footer>
</div>
</html>